config/routes.rb
Rails.application.routes.draw do

  resources :subjects
  resources :courses
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/user/courses', to: 'users#enrollments'
  post '/enroll/:code', to: 'users#enroll'
  get '/search', to: 'static_pages#search'
  get '/searchresults', to: 'static_pages#results'
  
  root 'sessions#new'
  get  '/signup',  to: 'users#new'
  
  resources :users
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def search
  end
  
  def results
  	@subject = params[:subject][:id]=='' ? nil : Subject.find(params[:subject][:id])
  	coursename = params[:q]
  	if @subject == nil
  		#@courses = Course.all
  		@courses = Course.where("name LIKE ?", "%#{coursename}%")
  		
  		
  	else
  		#@courses = @subject.courses
  		@courses = @subject.courses.where("name LIKE ?", "%#{coursename}%")
  	end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/results.html.erb
<% provide(:title, "Enrollments") %>
<p id="notice"><%= notice %></p>

<div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <li><%= link_to 'Search', search_path %></li>
        <li><%= link_to 'Home', user_courses_path %></li>
      </ul>
    </nav>
</div>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |c| %>
      <tr>
        <td><%= c.name %></td>
        <td><%= c.code %></td>
        <td><%= c.description %></td>
        <td><%= link_to "enroll", "/enroll/#{c.code}", method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/static_pages/search.html.erb
<% provide(:title, "Search") %>

<div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <li><%= link_to 'Search', search_path %></li>
        <li><%= link_to 'Home', user_courses_path %></li>
      </ul>
    </nav>
</div>

<h1>Searching results</h1>

<div>
<%= form_tag("/searchresults", method: "get") do %>
  <%= label_tag("Search for:") %>
  <%= "Course name:" %>
  <%= text_field_tag(:q) %>
  <%= "Subject:" %>
  <%= collection_select(:subject, :id, Subject.all, :id, :name, prompt: true) %>
  <%= submit_tag("Search") %>
<% end %>
</div>